export default Object.freeze({
  DASHBOARD: 'Home',
  ACCOUNT: 'Account',
  EDITPROFILE: 'Edit Profile',
  WELCOME: 'Welcome',
  LOGIN: 'Login',
  REGISTER: 'Register',
  TODO: 'Todos',
  NOTE: 'Notes',
  ADDNOTE: 'Add Note',
  CALENDAR: 'Calendar',
  ADDTODO: 'Add Todo',
  SINGLETODO: 'Single Todo',
  EDITTODO: 'Edit Todo',
  NOTESMAINSCREEN: 'NotesMainScreen',
  TODOSMAINSCREEN: 'TodosMainScreen',
  ACCOUNTMAINSCREEN: 'AccountMainScreen',
});
